name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn install
        uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: install
      - name: Build
        uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: build
      - name: Test
        uses: Borales/actions-yarn@v2.1.0
        with:
          cmd: test
      - name: Release
        run: |
          mkdir -p "$GITHUB_WORKSPACE/.temp/mnet-ui-base"        
          git clone "https://$GITHUB_ACTOR:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git" "$GITHUB_WORKSPACE/.temp/mnet-ui-base"
          cd "$GITHUB_WORKSPACE/.temp/mnet-ui-base"
          git checkout release
          ls -al
          find . \! -name '.git' -delete
          ls -al
          cp "$GITHUB_WORKSPACE/dist/" "$GITHUB_WORKSPACE/.temp/mnet-ui-base"
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"        
          git add .
          git commit -m "New Release"
          git remote set-url --push origin "https://$GITHUB_ACTOR:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git push

        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: ${{ secrets.GITHUB_ACTOR }}
